/**
 * A recipe's picture of the dish, as the running instance serves it.
 *
 * Each `describe` string is the proof id it satisfies. Every proof here asks the
 * COMPOSED instance (`composeInstance`, through `testInstanceDeps`), because the
 * claim is about what an operator's library shows, not about what the renderer
 * would show if somebody called it with a resolver.
 *
 * Four claims:
 *
 *  1. A recipe that has a picture shows it, on its page, on its library card and
 *     on the page the cooking address degrades to, and the address those pages
 *     name answers with the bytes the store holds.
 *  2. What that answer says the bytes are follows from the bytes alone. A stored
 *     file carries no label, and the one the publisher sent is that publisher's
 *     claim; bytes that are none of JPEG, PNG and WebP are not served at all,
 *     because a guessed type is how an HTML or SVG document stored as a
 *     "picture" would run as a page on this instance's origin.
 *  3. The address is the library's: without the library credential, and for
 *     every recipe with nothing to show, it is the one shared not-found answer.
 *  4. A recipe without a picture says so, in a sentence that is true for its
 *     source: a photographed cookbook page is not a picture of the dish
 *     (ontology §7), so its page says the photograph is the source, not that
 *     nothing was kept.
 *
 * No proof brings a picture from anywhere. Every image here is generated by
 * this file, a few bytes long, and is nobody's photograph.
 */
import { crc32, deflateSync } from "node:zlib"
import { html } from "hono/html"
import { describe, expect, it } from "vitest"
import { CanonicalRecipe, SourceSnapshot } from "../../schema/index.js"
import { servedImageType } from "../../src/http/image-signature.js"
import { NOT_FOUND_BODY } from "../../src/http/not-found.js"
import { NO_PICTURE_OF_THE_DISH } from "../../src/render/recipe-page.js"
import { composeInstance } from "../../src/server/instance.js"
import type { ByteStore } from "../../src/storage/index.js"
import { scratchByteStore } from "../support/scratch-byte-store.js"
import { canonical, LIBRARY_CREDENTIAL, testInstanceDeps } from "./harness.js"

// --- images made here ---------------------------------------------------------

const chunk = (type: string, data: Uint8Array): Buffer => {
  const typed = Buffer.concat([Buffer.from(type, "ascii"), data])
  const out = Buffer.alloc(12 + data.length)
  out.writeUInt32BE(data.length, 0)
  typed.copy(out, 4)
  out.writeUInt32BE(crc32(typed), 8 + data.length)
  return out
}

/** A real one-pixel PNG, built from the format's own parts. */
function onePixelPng(): Uint8Array {
  const header = Buffer.alloc(13)
  header.writeUInt32BE(1, 0) // width
  header.writeUInt32BE(1, 4) // height
  header.set([8, 2, 0, 0, 0], 8) // 8-bit truecolour, no interlace
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk("IHDR", header),
    chunk("IDAT", deflateSync(Buffer.from([0, 0xe0, 0x8a, 0x3c]))),
    chunk("IEND", new Uint8Array()),
  ])
}

/** The start of a JPEG: SOI, then an APP0 marker. Enough to be one by its signature. */
const jpegBytes = (): Uint8Array =>
  Uint8Array.from([0xff, 0xd8, 0xff, 0xe0, 0x00, 0x10, ...Buffer.from("JFIF\0"), 0x01, 0x01])

const webpBytes = (): Uint8Array =>
  Uint8Array.from([...Buffer.from("RIFF"), 0x1a, 0, 0, 0, ...Buffer.from("WEBPVP8L")])

const text = (s: string): Uint8Array => new TextEncoder().encode(s)

// --- the instance -------------------------------------------------------------

const auth = { authorization: `Bearer ${LIBRARY_CREDENTIAL}` }

interface Library {
  readonly app: ReturnType<typeof composeInstance>
  readonly repo: ReturnType<typeof testInstanceDeps>["repo"]
  readonly store: ByteStore
}

function library(): Library {
  const store = scratchByteStore().store
  const { deps, repo } = testInstanceDeps({ scanStore: store })
  return { app: composeInstance(deps), repo, store }
}

const get = (lib: Library, path: string, headers: Record<string, string> = auth) =>
  lib.app.request(path, { headers })

/** A recipe whose picture of the dish is `bytes`, kept in the instance's own store. */
async function withPicture(lib: Library, id: string, bytes: Uint8Array): Promise<CanonicalRecipe> {
  const storageIdentity = await lib.store.put(bytes)
  const recipe = CanonicalRecipe.parse({
    ...canonical(id, `Dish ${id}`),
    media: {
      heroImage: {
        storageIdentity,
        origin: "source_url",
        originalSourceUrl: "https://example.invalid/dish.png",
        attribution: "Fixture Kitchen",
      },
    },
  })
  await lib.repo.appendCanonicalVersion(recipe)
  return recipe
}

/** A recipe with no picture, from a snapshot of `sourceType` (or from none at all). */
async function withoutPicture(
  lib: Library,
  id: string,
  sourceType: "image" | "url" | "text" | undefined,
): Promise<CanonicalRecipe> {
  const base = canonical(id, `Dish ${id}`)
  const snapshotId = `snap-of-${id}`
  if (sourceType !== undefined) {
    await lib.repo.storeSnapshot(
      SourceSnapshot.parse({
        id: snapshotId,
        version: 0,
        sourceType,
        capturedText: "Mix and bake.",
        blocks: [{ id: "b-step", order: 0, type: "instruction", text: "Mix and bake." }],
        captureProvenance: {
          sourceAdapter: "fixture",
          adapterVersion: "1.0.0",
          runId: `capture-of-${id}`,
        },
      }),
    )
  }
  const recipe = CanonicalRecipe.parse({
    ...base,
    provenance: { ...base.provenance, sourceSnapshotId: snapshotId },
  })
  await lib.repo.appendCanonicalVersion(recipe)
  return recipe
}

/** The answer an address that does not exist gets, to compare every refusal with. */
async function sharedMiss(lib: Library) {
  return shape(await get(lib, "/no-such-address"))
}

async function shape(res: Response) {
  return {
    status: res.status,
    headers: Object.fromEntries(res.headers),
    body: Buffer.from(await res.arrayBuffer()).toString("latin1"),
  }
}

const href = (id: string) => `/recipes/${id}/picture`

/**
 * A sentence as a page carries it: escaped by the same template the pages use.
 * Measured: the photographed-page sentence holds an apostrophe, which arrives as
 * `&#39;`, so comparing the raw sentence finds nothing and a "not on the page"
 * assertion about it passes whatever the page says.
 */
const asServed = async (sentence: string): Promise<string> => String(await html`${sentence}`)

// --- 1. shown, and served -----------------------------------------------------

describe("picture/a-recipe-with-a-picture-shows-it", () => {
  it("names the recipe's picture address on its page, with the attribution", async () => {
    const lib = library()
    await withPicture(lib, "r-png", onePixelPng())

    const page = await (await get(lib, "/recipes/r-png")).text()
    expect(page, "the page does not show the picture").toContain(
      `<img src="${href("r-png")}" alt="Dish r-png">`,
    )
    expect(page).toContain('<p class="meta">Fixture Kitchen</p>')
    for (const absent of Object.values(NO_PICTURE_OF_THE_DISH)) {
      expect(page, "a page with a picture also says it has none").not.toContain(
        await asServed(absent),
      )
    }
  })

  it("names the same address on the recipe's library card", async () => {
    const lib = library()
    await withPicture(lib, "r-png", onePixelPng())

    const page = await (await get(lib, "/")).text()
    expect(page, "the library card does not show the picture").toContain(
      `<img src="${href("r-png")}"`,
    )
  })

  it("shows it on the page the cooking address degrades to", async () => {
    const lib = library()
    const recipe = await withPicture(lib, "r-broken", onePixelPng())
    // The real refusal, as `slice6/recipe-viewable-when-derivation-fails` uses
    // it: a step that uses an ingredient the recipe never declared.
    const [section] = recipe.instructionSections
    const [step] = section?.steps ?? []
    if (section === undefined || step === undefined) throw new Error("the fixture lost its step")
    await lib.repo.appendCanonicalVersion({
      ...recipe,
      instructionSections: [
        {
          ...section,
          steps: [
            {
              ...step,
              ingredientUses: [{ ingredientId: "ing-nobody", usage: "use_now", sourceRefs: [] }],
            },
          ],
        },
      ],
    })

    const page = await (await get(lib, "/recipes/r-broken/cook")).text()
    expect(page, "the degraded page dropped the picture").toContain(
      `<img src="${href("r-broken")}"`,
    )
  })

  it("answers that address with the bytes the store holds, typed by those bytes", async () => {
    const lib = library()
    const png = onePixelPng()
    await withPicture(lib, "r-png", png)
    await withPicture(lib, "r-jpeg", jpegBytes())
    await withPicture(lib, "r-webp", webpBytes())

    const served = await Promise.all(
      ["r-png", "r-jpeg", "r-webp"].map(async (id) => {
        const res = await get(lib, href(id))
        return {
          id,
          status: res.status,
          type: res.headers.get("content-type"),
          nosniff: res.headers.get("x-content-type-options"),
          cache: res.headers.get("cache-control"),
          length: (await res.arrayBuffer()).byteLength,
        }
      }),
    )
    const common = { status: 200, nosniff: "nosniff", cache: "no-store" }
    expect(served).toEqual([
      { id: "r-png", ...common, type: "image/png", length: png.length },
      { id: "r-jpeg", ...common, type: "image/jpeg", length: jpegBytes().length },
      { id: "r-webp", ...common, type: "image/webp", length: webpBytes().length },
    ])

    const bytes = new Uint8Array(await (await get(lib, href("r-png"))).arrayBuffer())
    expect(bytes, "the served bytes are not the stored ones").toEqual(new Uint8Array(png))
  })
})

// --- 2. typed by the bytes ----------------------------------------------------

describe("picture/the-type-follows-from-the-bytes", () => {
  it("reads the three formats from their signatures, and nothing else as any of them", () => {
    const table: [string, Uint8Array, string | undefined][] = [
      ["PNG", onePixelPng(), "image/png"],
      ["JPEG", jpegBytes(), "image/jpeg"],
      ["WebP", webpBytes(), "image/webp"],
      ["SVG", text('<svg xmlns="http://www.w3.org/2000/svg"><script/></svg>'), undefined],
      ["HTML", text("<!doctype html><script>alert(1)</script>"), undefined],
      ["GIF", text("GIF89a"), undefined],
      // What `#105` measured an iPhone sending under a JPEG label.
      ["HEIC", Uint8Array.from([0, 0, 0, 0x18, ...text("ftypheic")]), undefined],
      [
        "a RIFF that is audio",
        Uint8Array.from([...text("RIFF"), 0, 0, 0, 0, ...text("WAVE")]),
        undefined,
      ],
      ["PNG cut inside its signature", onePixelPng().slice(0, 7), undefined],
      ["JPEG cut inside its signature", jpegBytes().slice(0, 2), undefined],
      ["nothing", new Uint8Array(), undefined],
    ]
    expect(table.map(([name, bytes]) => [name, servedImageType(bytes)])).toEqual(
      table.map(([name, , type]) => [name, type]),
    )
  })

  it("does not serve stored bytes that are no image it knows, whatever the record says", async () => {
    const lib = library()
    await withPicture(lib, "r-svg", text('<svg xmlns="http://www.w3.org/2000/svg"><script/></svg>'))
    await withPicture(lib, "r-html", text("<!doctype html><script>alert(1)</script>"))
    const miss = await sharedMiss(lib)

    expect(await shape(await get(lib, href("r-svg")))).toEqual(miss)
    expect(await shape(await get(lib, href("r-html")))).toEqual(miss)
  })
})

// --- 3. the library's address -------------------------------------------------

describe("picture/the-address-is-the-librarys", () => {
  it("is the shared not-found answer without the library credential", async () => {
    const lib = library()
    await withPicture(lib, "r-png", onePixelPng())
    const miss = await sharedMiss(lib)

    expect(await shape(await get(lib, href("r-png"), {}))).toEqual(miss)
    expect(await shape(await get(lib, href("r-png"), { authorization: "Bearer wrong" }))).toEqual(
      miss,
    )
  })

  it("is the shared not-found answer for every recipe with nothing to show", async () => {
    const lib = library()
    await withoutPicture(lib, "r-none", "url")
    // A record naming bytes the store does not hold: the identity is the
    // store's own spelling, issued by a different store.
    const elsewhere = await scratchByteStore().store.put(onePixelPng())
    const recipe = canonical("r-lost", "Dish r-lost")
    await lib.repo.appendCanonicalVersion(
      CanonicalRecipe.parse({
        ...recipe,
        media: { heroImage: { storageIdentity: elsewhere, origin: "source_url" } },
      }),
    )
    // And one the store could never have issued.
    await lib.repo.appendCanonicalVersion(
      CanonicalRecipe.parse({
        ...canonical("r-crafted", "Dish r-crafted"),
        media: { heroImage: { storageIdentity: "../../etc/passwd", origin: "other" } },
      }),
    )
    const miss = await sharedMiss(lib)
    expect(miss.body).toBe(NOT_FOUND_BODY)

    for (const id of ["r-none", "r-lost", "r-crafted", "nobody"]) {
      expect({ id, ...(await shape(await get(lib, href(id)))) }).toEqual({ id, ...miss })
    }
  })
})

// --- 4. no picture, said truthfully -------------------------------------------

describe("picture/no-picture-is-a-stated-gap", () => {
  /** Which of the stated gaps the page says, as its reason; exactly one is required. */
  const gapOn = async (lib: Library, id: string): Promise<string | undefined> => {
    const page = await (await get(lib, `/recipes/${id}`)).text()
    expect(page, `the page of ${id} shows a picture it does not have`).not.toContain("<img")
    const gaps = await Promise.all(
      Object.entries(NO_PICTURE_OF_THE_DISH).map(async ([reason, sentence]) => ({
        reason,
        paragraph: `<p class="meta source-gap">${await asServed(sentence)}</p>`,
      })),
    )
    const said = gaps.filter((gap) => page.includes(gap.paragraph)).map((gap) => gap.reason)
    expect(said.length, `the page of ${id} states ${said.length} picture gaps`).toBe(1)
    return said[0]
  }

  it("says a photographed page is the source, not a picture of the dish", async () => {
    const lib = library()
    await withoutPicture(lib, "r-photo", "image")
    expect(await gapOn(lib, "r-photo")).toBe("photographed_page")
  })

  it("says none was kept for a linked page, a pasted text, and a snapshot it cannot find", async () => {
    const lib = library()
    await withoutPicture(lib, "r-url", "url")
    await withoutPicture(lib, "r-text", "text")
    await withoutPicture(lib, "r-orphan", undefined)

    const said = await Promise.all(
      ["r-url", "r-text", "r-orphan"].map(async (id) => [id, await gapOn(lib, id)]),
    )
    expect(said).toEqual([
      ["r-url", "none_kept"],
      ["r-text", "none_kept"],
      ["r-orphan", "none_kept"],
    ])
  })
})
